const EErrors = {
  INVALID_TYPES_ERROR: 'INVALID_TYPES_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  NOT_FOUND_ERROR: 'NOT_FOUND_ERROR',
  AUTH_ERROR: 'AUTH_ERROR',
  FORBIDDEN_ERROR: 'FORBIDDEN_ERROR'
};

module.exports = EErrors;